version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: heaven_python_api
    restart: always
    ports:
      - "3009:3009"
    env_file:
      - ./backend/.env
    volumes:
      - uploads_data:/app/app/static/uploads
    networks:
      - heaven_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: heaven_python_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - heaven_network

volumes:
  uploads_data:

networks:
  heaven_network:
    driver: bridge
